services:
  pgsql:
    container_name: pgsql
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - playlist-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DATABASE_NAME}", "-U", "${DATABASE_USER}"]
      retries: 3
      timeout: 5s
    networks:
      - playlist-network

  backend:
    container_name: backend
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      pgsql:
        condition: service_healthy
    volumes:
      - playlist:/app
    networks:
      - playlist-network

volumes:
  playlist-db:
  playlist:

networks:
  playlist-network:
    driver: bridge
      