name: Deploy Playlist books backend

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout do código
              uses: actions/checkout@v3

            - name: Criar pacote para envio
              run: tar -czf backend.tar.gz Dockerfile docker-compose.yml src package.json tsconfig.json .env.example

            - name: Enviar pacote para servidor EC2 AWS
              env: 
                SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                EC2_HOST: ${{ secrets.EC2_HOST }}
                EC2_USER: ${{ secrets.EC2_USER }}
              run: |
                printf "%s" "$SSH_PRIVATE_KEY" > private_key.pem
                chmod 600 private_key.pem
                scp -i private_key.pem -o StrictHostKeyChecking=no backend.tar.gz $EC2_USER@$EC2_HOST:/home/$EC2_USER/

            - name: Conectar ao servidor EC2 AWS e configurar backend
              env:
                SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                EC2_HOST: ${{ secrets.EC2_HOST }}
                EC2_USER: ${{ secrets.EC2_USER }}
              run: |
                ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
                
                # Navegar para a pasta do backend
                cd /home/$EC2_USER/
                              
                # Verificar se o arquivo foi transferido corretamente
                ls -l backend.tar.gz
                              
                # Parar e remover containers existentes
                docker-compose down
                              
                # Remover arquivos antigos e extrair os novos
                rm -rf backend
                sudo mkdir -p /home/ubuntu/backend
                              
                # Extrair o arquivo tar.gz
                sudo tar -xzf backend.tar.gz -C backend
                              
                # Verificar se o arquivo docker-compose.yml está presente
                ls -l /home/ubuntu/backend/docker-compose.yml
                              
                # Garantir permissões corretas no diretório
                sudo chown -R $EC2_USER:$EC2_USER /home/ubuntu/backend
                sudo chmod -R 755 /home/ubuntu/backend
                              
                # Criar o .env com as variáveis de ambiente seguras
                echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" > .env | sudo tee -a /home/ubuntu/backend/.env > /dev/null
                echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env | sudo tee -a /home/ubuntu/backend/.env > /dev/null
                echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env | sudo tee -a /home/ubuntu/backend/.env > /dev/null
                echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env | sudo tee -a /home/ubuntu/backend/.env > /dev/null
                echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env | sudo tee -a /home/ubuntu/backend/.env > /dev/null
                echo 'DATABASE_SCHEMA="${{ secrets.DATABASE_SCHEMA }}"' >> .env | sudo tee -a /home/ubuntu/backend/.env > /dev/null
                echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env | sudo tee -a /home/ubuntu/backend/.env > /dev/null
                echo "GOOGLE_BOOKS_KEY=${{ secrets.GOOGLE_BOOKS_KEY }}" >> .env | sudo tee -a /home/ubuntu/backend/.env > /dev/null
                              
                # Construir e rodar os containers
                docker-compose up --build -d
                EOF
